
services:
  db:
    image: postgres:15.6-alpine3.19
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=flagdb
    # BUG: No volume! Data disappears on restart!
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build: ./app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/flagdb

# TODO: Add volumes section
